export const ACTIONS =  {
    SET_FULLBOX_ON : "SET_FULLBOX_ON",
    SET_FULLBOX_OFF : "SET_FULLBOX_OFF",
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
    CART_CLEAR: 'CART_CLEAR',
    USER_SIGNIN: 'USER_SIGNIN',
    USER_SIGNOUT: 'USER_SIGNOUT',
    SAVE_SHIPPING_ADDRESS:'SAVE_SHIPPING_ADDRESS',
    SAVE_SHIPPING_ADDRESS_MAP_LOCATION: "SAVE_SHIPPING_ADDRESS_MAP_LOCATION",
    SAVE_PAYMENT_METHOD: 'SAVE_PAYMENT_METHOD'
}